### ISSUE TITLE
Plugins - MapWindow

### ISSUE THREAD

**Issue by saraneh** [MapWindow/MapWindow5#26]
Hiya,
I am new to both Github and MapWindow. I was wondering how to access the plugins?
I see that there are options in the Configure Plugins Menu, but how does one actually access these plugins for use?
Thanks!

**Comment by pmeems** [comment]
Most plug-ins are loaded at start-up:
![image](https://user-images.githubusercontent.com/12067729/36325079-d92dfdde-1356-11e8-83ec-9674402fd28a.png)

At (1) you can open the plugins settings form (2).
(3) is the data repository, (4) the debug window.
(5) is the GIS Toolbox, (6) the identifier.
(7) are the two buttons of the printing plug-in.
(8) is the shape editor. Currently disabled because no shapefile data loaded.
(9) is the symbology editor, (10) the table editor.

Is this what you are looking for?

**Comment by saraneh** [comment]
Hi Paul!
Thanks very much for your response, yes that clarifies where the plugins are!
On a related note, do you know if there are many additional plugins out there created for MapWindow that have been created by users?
