### ISSUE TITLE
SyncFusion Licensing

### ISSUE THREAD

**Issue by dhuantes** [MapWindow/MapWindow5#30]
Paul, et. al.,

Just recently moving back onto a few sprints on a project that uses MapWindow5.  I have a new dev machine and MapWindow5 was complaining about missing Syncfusion references when I tried to build it so I went to SyncFusion's website (as I think I did before) and downloaded the Windows Forms controls distribution.  

I've since been e-mailed by a SyncFusion rep indicating that despite MapWindow having an agreement with SyncFusion my company does not so I will need to purchase licenses to use their controls.  What does the agreement that MapWindow has with SyncFusion actually say?   I think I can get by without building MapWindow5 and just building my plugin without SyncFusion references but this just seems wrong from an OpenSource perspective.   Let me know.  Thanks!

**Comment by pmeems** [comment]
Hi Dan,

We use the community edition now. Do you still need a license key for that?
I've set it up years ago, so I don't remember ;)

And you're right for building plug-ins you don't need to rebuild MapWindow5, you can just download it. And then you don't need the SyncFusion controls separately because they are shipped with MW5 already.
